[font]
size = 9.0

[font.normal]
family = "OpenDyslexicMNerdFontMono"
style = "Regular"

[scrolling]
history = 5000
multiplier = 3

[general]
#import = ["./tokyo-night.toml"]
import = ["./gruvbox.toml"]
